<?php
namespace common\model;
use kali\core\log;
use kali\core\util;


/**
 * @ClassName: mod_down_file
 * @Author: Gangkui
 * @Date: 2019-01-21 11:03:24
 */
class mod_send_goods extends mod_base
{

    public static $_table = '#PB#_send_goods';

    public static $_pk = 'id';

    public static $_field = [
        'go_off', 'car_number', 'member_id', 'goods_inter','balance',
        'create_time'
    ];

    public static function save($data, $where = [])
    {
        $result = parent::save($data, $where); // TODO: Change the autogenerated stub

        if(empty($where) && empty($data[self::$_pk]) && $result)
        {
            $member_info = mod_member::getdump([[mod_member::$_pk, '=', $data['member_id']]]);
            $date = date('Y-m-d H:i:s', $data['go_off']);
            $content = "尊敬的{$member_info['username']} 先生/女生，您的货物已于{$date}装车并出发，车牌号码是：{$data['car_num']},账户余额{$data['balance']},祝您生活愉快";
            self::send_sms($member_info['mobile'], $content);
            $content = "尊敬的{$member_info['username']} 先生/女生，您的货物备注说明：{$data['goods_inter']}，祝您生活愉快！";
            self::send_sms($member_info['mobile'], $content);
        }

        return $result;
    }


    public static function send_sms($mobile,$content)
    {
        $appid = 'cf_uli9';
        $appkey = 'c4c283a827cb585e9c3d4db5c9d8a997';
        //短信接口地址
        $target = "http://106.ihuyi.com/webservice/sms.php?method=Submit";
        $post_data = "account={$appid}&password={$appkey}&mobile={$mobile}&content=".rawurlencode($content);
        $res = util::http_post($target, $post_data);

        log::info('发货短信通知结果: ' . var_export($res, 1) . '：短信发送信息：' .  var_export($content, 1), __METHOD__);
    }
}